// Copyright (C) 2026 Piovium Labs
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.

import { renderToString } from "solid-js/web";

import { FlowDiagramSvg } from "./FlowDiagramSvg";
import type { LayoutedFlowDiagram } from "./layout";

export function renderFlowDiagramSvg(layout: LayoutedFlowDiagram): string {
  const svg = renderToString(() => (
    <FlowDiagramSvg layout={layout} staticSize />
  ));
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    "<!-- Generated by @gi-tcg/process-viewer. Do not edit directly. -->",
    svg,
    "",
  ].join("\n");
}
