// Copyright (C) 2026 Piovium Labs
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

import {
  ref,
  setup,
  Character,
  State,
  Card,
  Summon,
  Status,
  CombatStatus,
  $,
} from "#test";
import { TandooriRoastChicken } from "@gi-tcg/data/internal/cards/event/food.gts";
import {
  ElementalLifeformHydro,
  FlowConvergence,
  HalfTulpa01,
  HalfTulpa02,
  HalfTulpa03,
  HalfTulpa04,
  HydroTulpa,
  StormSurge,
  ThunderingTide,
} from "@gi-tcg/data/internal/characters/hydro/hydro_tulpa.gts";
import { GoldenChalicesBounty } from "@gi-tcg/data/internal/characters/hydro/nilou.gts";
import { CoolYourJetsDucky } from "@gi-tcg/data/internal/characters/hydro/aino.gts";
import {
  Barbara,
  WhisperOfWater,
} from "@gi-tcg/data/internal/characters/hydro/barbara.gts";
import {
  Fischl,
  Nightrider,
} from "@gi-tcg/data/internal/characters/electro/fischl.gts";
import { AegisOfAbyssalFlame } from "@gi-tcg/data/internal/characters/pyro/abyss_lector_fathomless_flames.gts";
import { Crystallize, Frozen } from "@gi-tcg/data/internal/commons.gts";
import { Aura } from "@gi-tcg/typings";
import { test } from "vitest";

test("hydro tulpa: E can be increaseSkillDamage'd", async () => {
  const tulpa = ref();
  const target = ref();
  const c = setup(
    <State>
      <Character opp active health={10} ref={target} />
      <Character my active def={HydroTulpa} ref={tulpa} />
      <Card my def={TandooriRoastChicken} />
    </State>,
  );
  await c.me.card(TandooriRoastChicken);
  await c.me.skill(StormSurge);
  c.expect(target).toHaveVariable({ health: 6 });
});

test("storm surge: skill itself gives no energy, the passive grants 1 energy after use", async () => {
  // 规则集：汛波：此技能不产生充能；汛波①：角色使用【汛波】后：获得1点充能
  // 断言：0 充能使用汛波后恰为 1 点充能
  const tulpa = ref();
  const c = setup(
    <State>
      <Character opp active health={10} />
      <Character my active def={HydroTulpa} ref={tulpa} energy={0} />
    </State>,
  );
  await c.me.skill(StormSurge);
  c.expect(tulpa).toHaveVariable({ energy: 1 });
});

test("storm surge: triggers the end phase effect of my (only) summon", async () => {
  // 规则集：汛波①：随机触发我方1个【召唤物】的【结束阶段】效果
  // 断言：只有 1 个召唤物时必定触发它：对方 10 - 2（汛波）- 1（半幻人）= 7，半幻人可用次数 2 -> 1
  const target = ref();
  const halfTulpa = ref();
  const c = setup(
    <State>
      <Character opp active health={10} ref={target} />
      <Character my active def={HydroTulpa} health={10} />
      <Summon my def={HalfTulpa01} ref={halfTulpa} usage={2} />
    </State>,
  );
  await c.me.skill(StormSurge);
  c.expect(target).toHaveVariable({ health: 7 });
  c.expect(halfTulpa).toHaveVariable({ usage: 1 });
});

test("storm surge: self piercing damage happens even without any summon", async () => {
  // 规则集：没有召唤物也会对自己造成1点伤害
  // 断言：无召唤物时对方受到 2 点，水形幻人自身受到 1 点穿透伤害
  const target = ref();
  const tulpa = ref();
  const c = setup(
    <State>
      <Character opp active health={10} ref={target} />
      <Character my active def={HydroTulpa} ref={tulpa} health={10} />
    </State>,
  );
  await c.me.skill(StormSurge);
  c.expect(target).toHaveVariable({ health: 8 });
  c.expect(tulpa).toHaveVariable({ health: 9 });
});

test("storm surge: no self damage when health is below 2", async () => {
  // 规则集：造成2点水元素伤害。若角色生命值不低于2，受到1点穿透伤害。
  // 断言：1 血时不受穿透伤害
  const tulpa = ref();
  const c = setup(
    <State>
      <Character opp active health={10} />
      <Character my active def={HydroTulpa} ref={tulpa} health={1} />
    </State>,
  );
  await c.me.skill(StormSurge);
  c.expect(tulpa).toHaveVariable({ health: 1, alive: 1 });
});

test("thundering tide: triggers the end phase effect of all my summons", async () => {
  // 规则集：洪啸①：角色使用【洪啸】后：触发我方所有【召唤物】的【结束阶段】效果
  // 断言：对方 10 - 4 - 1 - 1 = 4，两个半幻人可用次数各 2 -> 1
  const target = ref();
  const half1 = ref();
  const half2 = ref();
  const c = setup(
    <State>
      <Character opp active health={10} ref={target} />
      <Character my active def={HydroTulpa} energy={3} />
      <Summon my def={HalfTulpa01} ref={half1} usage={2} />
      <Summon my def={HalfTulpa02} ref={half2} usage={2} />
    </State>,
  );
  await c.me.skill(ThunderingTide);
  c.expect(target).toHaveVariable({ health: 4 });
  c.expect(half1).toHaveVariable({ usage: 1 });
  c.expect(half2).toHaveVariable({ usage: 1 });
});

test("thundering tide: a summon generated by the skill's damage is also triggered", async () => {
  // 规则集：汛波和洪啸，造成伤害和触发召唤物是分开的效果（为了让技能生成的召唤物能被触发）
  // 场景：金杯的丰馈在场，洪啸对草附着目标绽放 -> 召唤丰穰之核 -> 随后被洪啸触发结束阶段效果
  // 断言：对方 10 - (4+1 绽放) - 2（丰穰之核）= 3
  const target = ref();
  const c = setup(
    <State>
      <Character opp active health={10} ref={target} aura={Aura.Dendro} />
      <Character my active def={HydroTulpa} energy={3} health={10} />
      <CombatStatus my def={GoldenChalicesBounty} />
    </State>,
  );
  await c.me.skill(ThunderingTide);
  c.expect(target).toHaveVariable({ health: 3 });
});

test("storm surge: summons are not triggered if the damage's aftermath defeats hydro tulpa", async () => {
  // 规则集：如果造成伤害被钻头-弹片等方式击杀，是无法触发召唤物效果的。
  // 场景：对方渊火加护（护盾 2）被汛波打空 -> 对我方全体 1 点穿透 -> 1 血的水形幻人被击倒
  // 断言：半幻人未被触发（可用次数仍为 2），对方生命不变
  const target = ref();
  const tulpa = ref();
  const halfTulpa = ref();
  const c = setup(
    <State>
      <Character opp active health={10} ref={target}>
        <Status def={AegisOfAbyssalFlame} />
      </Character>
      <Character my active def={HydroTulpa} ref={tulpa} health={1} />
      <Summon my def={HalfTulpa01} ref={halfTulpa} usage={2} />
    </State>,
  );
  await c.me.skill(StormSurge);
  c.expect(tulpa).toHaveVariable({ alive: 0 });
  c.expect(target).toHaveVariable({ health: 10 });
  c.expect(halfTulpa).toHaveVariable({ usage: 2 });
});

test("elemental lifeform hydro: applies hydro twice on entry", async () => {
  // 规则集：①入场时：附着水元素2次
  // 场景：水形幻人附着冰元素时打出汇流
  // 断言：第 1 次水附着触发冻结（附着被消耗），第 2 次水附着使其重新附着水元素
  const tulpa = ref();
  const c = setup(
    <State>
      <Character opp active />
      <Character my active def={HydroTulpa} ref={tulpa} aura={Aura.Cryo} />
      <Card my def={FlowConvergence} />
    </State>,
  );
  await c.me.card(FlowConvergence, tulpa);
  c.expect($.my.typeStatus.def(ElementalLifeformHydro)).toBeExist();
  c.expect($.my.typeStatus.def(Frozen)).toBeExist();
  c.expect(tulpa).toHaveVariable({ aura: Aura.Hydro });
});

test.fails("elemental lifeform hydro: with cryo+dendro aura, two hydro applications leave no hydro", async () => {
  // 规则集：同时附着 冰草元素的场合，只能进行两次水附着，最后没有水附着残余；
  //   当前引擎：元素生命·水的 on modifyReaction 无 when 条件，任何反应后都补附着水（不区分被消耗的是否为原本附着的水），
  //   入场附着 -> 冻结（剩草）-> 补附着 -> 绽放 -> 再补附着，共 3 次附着，最终残余水元素
  // 断言：冰草共存时入场的 2 次水附着分别触发冻结、绽放，最终无附着
  const tulpa = ref();
  const c = setup(
    <State>
      <Character opp active />
      <Character my active def={HydroTulpa} ref={tulpa} aura={Aura.CryoDendro} />
      <Card my def={FlowConvergence} />
    </State>,
  );
  await c.me.card(FlowConvergence, tulpa);
  c.expect(tulpa).toHaveVariable({ aura: Aura.None });
});

test("elemental lifeform hydro: hydro is not consumed when the original hydro aura reacts", async () => {
  // 规则集：②角色原本附着水元素被触发元素反应时：不消耗水元素
  // 断言：菲谢尔夜巡影翼 1 雷伤 -> 感电（+1）后水形幻人仍附着水元素
  const tulpa = ref();
  const c = setup(
    <State currentTurn="opp">
      <Character opp active def={Fischl} />
      <Character my active def={HydroTulpa} ref={tulpa} health={10} aura={Aura.Hydro}>
        <Status def={ElementalLifeformHydro} />
      </Character>
    </State>,
  );
  await c.opp.skill(Nightrider);
  c.expect(tulpa).toHaveVariable({ health: 8, aura: Aura.Hydro });
});

test("elemental lifeform hydro: hydro immunity is a normal damage reduction, shield is untouched", async () => {
  // 规则集：③受到水元素伤害时：伤害-9999；“免疫”是普通的减伤，跟莲花酥等同时机。
  // 断言：芭芭拉 1 点水伤被减到 0，水形幻人不掉血，且结晶护盾（减伤之后才结算）不被消耗
  const tulpa = ref();
  const c = setup(
    <State currentTurn="opp">
      <Character opp active def={Barbara} />
      <Character my active def={HydroTulpa} ref={tulpa} health={10} aura={Aura.Hydro}>
        <Status def={ElementalLifeformHydro} />
      </Character>
      <CombatStatus my def={Crystallize} shield={1} />
    </State>,
  );
  await c.opp.skill(WhisperOfWater);
  c.expect(tulpa).toHaveVariable({ health: 10 });
  c.expect($.my.combatStatus.def(Crystallize)).toHaveVariable({ shield: 1 });
});

test("branching flow: still triggers when the summon zone is full", async () => {
  // 规则集：分流 注：召唤区已满也能发动
  // 场景：召唤区 3 个半幻人 + 冷静一下鸭（可用次数 1）已满，结束阶段鸭子耗尽离场
  // 断言：分流仍发动：水形幻人受到 2 点穿透伤害，召唤第 4 个半幻人
  const tulpa = ref();
  const c = setup(
    <State>
      <Character opp active health={20} />
      <Character my active />
      <Character my def={HydroTulpa} ref={tulpa} health={10} />
      <Summon my def={HalfTulpa01} usage={2} />
      <Summon my def={HalfTulpa02} usage={2} />
      <Summon my def={HalfTulpa03} usage={2} />
      <Summon my def={CoolYourJetsDucky} usage={1} />
    </State>,
  );
  await c.me.end();
  await c.opp.end();
  c.expect($.my.summon.def(CoolYourJetsDucky)).toNotExist();
  c.expect(tulpa).toHaveVariable({ health: 8 });
  c.expect($.my.summon.def(HalfTulpa04)).toBeExist();
});
